### PR TITLE
DOC: Improve user-facing documentation

### PR DESCRIPTION
**Pull request by pllim**
As requested by @mustaric .

# TODO

- [x] Re-organize sections.
- [x] Fix formatting: Heading level uneven, narrative + API mix hard to read.
- [ ] Improve docstring.

### CODE REVIEW

**Review by mustaric — APPROVED** [review]
This looks like a really good start. I don't have strong opinions on the organization, so if you like it, then I think we can go for it.  If you have places where you are unsure we could discuss it.

**Comment by pllim** [comment]
Currently, the rendered API doc for `vetters.py` is wrong due to #54

**Comment by mustaric** [comment]
The rendered version of this looks good.  There are places where I really should write better documentation about what each of these vetters do. I didn't see anything wrong, it is just very terse.  I'd say go ahead and merge when you are ready.

**Comment by pllim** [comment]
Okay, I merged it. Thanks for the review! I'll continue in a separate PR after #54 is resolved.

**Pull request merged**
