### PR TITLE
Fm modshift

### PR DESCRIPTION
**Pull request by fergalm**
Modshift metrics.

### CODE REVIEW

**Review by pllim — COMMENTED** [review]
@fergalm , is this ready for review or are you still working on it?

Before review, would be nice to:

* Squash the commits.
* Rebase against current `master`.
* Fix the tests.
* If there is any file that is set to executable, do a `chmod 644` on them. Besides `setup.py`, I don't see why we need them to be executable. Not sure if you have those here but I notice a lot of them in previous PRs that got merged.
* Not sure why we need `# -*- coding: utf-8 -*-`. Is this a leftover from Python 2? Can we remove them?

Thanks!

**Comment by mustaric** [comment]
@pllim  can you make a recommendation about how to get this pull request past the tests.  It looks like it doesn't want there to be any assert statements in the code. The assert statements that Fergal uses look reasonable to me, so I don't understand why they shouldn't be part of the code.  Is there a better way to accomplish the same thing, or can we just remove the CI test that looks for asserts?

Anything you can do to get this branch to merge successfully would be helpful.

**Comment by pllim** [comment]
@mustaric and @fergalm , I fixed the tests for you. Ignored the canceled jobs. Coverage did fall and I noticed that there are comments about "this doesn't work" or "this isn't really what I want," but if you want to merge despite those comments anyway, then you can now.

**Comment by pllim** [comment]
Update: Resolved conflict.

**Pull request merged**
