### PR TITLE
added a phase coverage vetter

### LINKED ISSUE #22: Add Phase Coverage vetter
Add a vetter that returns the fraction of the folded transit that contains data. Sparsely sampled transits end to be noise.   This requires knowing the duration of the tce.

### PR DESCRIPTION
**Pull request by mustaric**
A start on a simple coverage vetter. It still needs to be added to the vetters.py and tests moved to the correct place.

EDIT: Fix #22

### CODE REVIEW

**Comment by pllim** [comment]
Tip: Instead of "do not merge" label, which still allows accidental merging, it is safer to turn this into a draft PR, which disables the merge button completely. When you are ready, you can convert it to a "normal" PR with one click. This does not affect the CI. I'll turn it into a draft PR for you now.

**Comment by mustaric** [comment]
I'll try to remember that (assuming I can find the button). I'm not sure how I see how to change it back to a normal PR,  so when the time comes I'll need you to show me that one click button.

**Comment by pllim** [comment]
It is the "Ready for Review" button.

**Comment by mustaric** [comment]
We will save creating the vetting class for another pull request.

**Pull request merged**
