### PR TITLE
Simple odd Even test

### PR DESCRIPTION
**Pull request by mustaric**
Here is code for a simple average based odd/even vetter. 
 I haven't added it to the vetter class yet.  I'd like that done in a separate pull request. 

EDIT: Address part of #23

### CODE REVIEW

**Comment by pllim** [comment]
Why not do it all in one PR? Anyways, feel free to ping me when you think this is ready for review. Might want to fix the CI first. Thanks!

**Comment by mustaric** [comment]
So somehow a file ended up in this branch that should not be tracked by this branch...it will be added in the other pull request, the transit coverage one.  How do I remove it from this pull request without removing it from the other branch.

**Comment by pllim** [comment]
> How do I remove it from this pull request without removing it from the other branch.

What you do to this branch should not matter to the other branch. You might want to squash the commits after you remove file from this branch to purge it from history in this branch.

**Comment by mustaric** [comment]
My reluctance to add to the vetter class in this PR is because I likely will not get to it for a while and this is a good stopping point. Maybe it is really my hope that someone else will take on that task if I don't get to it.  Anyhow, this has passed CI, so take a look and let me know if it looks okay.  @fergalm might also want to take a look.

**Pull request merged**
